// react/src/components/Tree/tree.jsx
import './tree.scss';
import NodeList from './nodeList';
import { useEffect, useState } from 'react';
import {
  arrAdd,
  arrDel,
  flattenTreeData,
  convertDataToEntities
} from './treeUtil';

function Tree(props) {
  const {
    treeData,
    fieldNames = { key: 'key', title: 'title', children: 'children' }
  } = props;

  const [keyEntities, setKeyEntities] = useState({});
  const [expandedKeys, setExpandedKeys] = useState([]);
  const [flattenNodes, setFlattenNodes] = useState([]);

  const setExpandedKeysAndFlattenNodes = expandedKeys => {
    const flattenNodes = flattenTreeData(treeData, expandedKeys, fieldNames);

    setExpandedKeys(expandedKeys);
    setFlattenNodes(flattenNodes);
  };

  const onNodeExpand = (e, treeNode) => {
    const { expanded } = treeNode;
    const key = treeNode[fieldNames.key];
    const targetExpanded = !expanded;

    if (targetExpanded) {
      setExpandedKeysAndFlattenNodes(arrAdd(expandedKeys, key));
    } else {
      setExpandedKeysAndFlattenNodes(arrDel(expandedKeys, key));
    }
  };

  const initExpandedKeys = () => {
    let expandedKeys = [];
    setExpandedKeys(expandedKeys);
    return expandedKeys;
  };

  const initKeyEntities = () => {
    const entitiesMap = convertDataToEntities(treeData, { fieldNames });
    setKeyEntities(entitiesMap.keyEntities);
    return entitiesMap.keyEntities;
  };

  const initFlattenNodes = expandedKeys => {
    const flattenNodes = flattenTreeData(
      treeData,
      expandedKeys,
      fieldNames || {}
    );
    setFlattenNodes(flattenNodes);
  };

  const initData = () => {
    const keyEntities = initKeyEntities();
    const expandedKeys = initExpandedKeys(keyEntities);
    initFlattenNodes(expandedKeys);
  };

  useEffect(() => {
    initData();
  }, []);

  return (
    <div className={`tree`}>
      <NodeList
        data={flattenNodes}
        keyEntities={keyEntities}
        expandedKeys={expandedKeys}
        onNodeExpand={onNodeExpand}
      />
    </div>
  );
}

export default Tree;

// vue3/src/components/RcTree/Tree.tsx
import './tree.scss';
import NodeList from './NodeList';
import { TreeProps } from './treeProps';
import { useProvideKeysState } from './contextTree';
import {
  fillFieldNames,
  flattenTreeData,
  initDefaultProps,
  convertDataToEntities,
  arrAdd,
  arrDel
} from './treeUtil';
import {
  watch,
  toRaw,
  computed,
  watchEffect,
  shallowRef,
  defineComponent
} from 'vue';

export default defineComponent({
  name: 'Tree',
  props: initDefaultProps(TreeProps(), {
    treeData: [],
    children: [],
    fieldNames: { key: 'key', title: 'title', children: 'children' }
  }),
  setup(props) {
    const treeData = shallowRef([]);
    const keyEntities = shallowRef({});
    const flattenNodes = shallowRef([]);
    const expandedKeys = shallowRef([]);

    const fieldNames = computed(() => fillFieldNames(props.fieldNames));

    const setExpandedKeys = newExpandedKeys => {
      expandedKeys.value = newExpandedKeys;
    };

    const onNodeExpand = (e, treeNode) => {
      const { expanded } = treeNode;
      const key = treeNode[fieldNames.value.key];
      const targetExpanded = !expanded;

      if (targetExpanded) {
        setExpandedKeys(arrAdd(expandedKeys.value, key));
      } else {
        setExpandedKeys(arrDel(expandedKeys.value, key));
      }
    };

    watch(
      () => props.treeData,
      () => {
        treeData.value = toRaw(props.treeData);
      },
      {
        deep: true,
        immediate: true
      }
    );

    watchEffect(() => {
      if (treeData.value) {
        const entitiesMap = convertDataToEntities(treeData.value, {
          fieldNames: fieldNames.value
        });
        keyEntities.value = entitiesMap.keyEntities;
      }
    });

    watchEffect(() => {
      flattenNodes.value = flattenTreeData(
        treeData.value,
        expandedKeys.value,
        fieldNames.value
      );
    });

    useProvideKeysState({
      expandedKeys,
      flattenNodes,
      keyEntities,
      onNodeExpand
    });

    return () => {
      return (
        <div class="tree">
          <NodeList />
        </div>
      );
    };
  }
});
